apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfryeew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfryeew
  template:
    metadata:
      labels:
        app: dfryeew
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: dfryeew
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "110fbebe-f5c9-475f-ae61-f89e2047b1a0 "
        - name: Vless_Path
          value: "/vl5dfgrt55"
        - name: Vmess_UUID
          value: "110fbebe-f5c9-475f-ae61-f89e2047b1a0 "
        - name: Vmess_Path
          value: "/vmetyu666"
        - name: Share_Path
          value: "/v2link"
